[project]
name = "nfm"
version = "0.1.0"
authors = [{ name = "Matěj Pekár", email = "matejpekar@mail.muni.cz" }]
requires-python = ">=3.12,<3.13"
readme = "README.md"
license = { file = "LICENSE" }
dependencies = [
    "torch>=2.5.1",
    "lightning>=2.4.0",
    "torchmetrics>=1.4.1",
    "rationai-mlkit>=0.2.0",
    "psutil>=7.0.0",
    "pynvml>=12.0.0",
    "torch-geometric>=2.6.1",
]

[tool.uv]
dev-dependencies = ["mypy", "pre-commit", "ruff"]

[tool.uv.sources]
rationai-mlkit = { git = "https://gitlab.ics.muni.cz/rationai/digital-pathology/libraries/mlkit.git" }
rationai-masks = { git = "https://gitlab.ics.muni.cz/rationai/digital-pathology/libraries/masks.git" }
rationai-tiling = { git = "https://gitlab.ics.muni.cz/rationai/digital-pathology/libraries/tiling.git" }
rationai-kube-jobs = { git = "ssh://git@gitlab.ics.muni.cz/rationai/digital-pathology/libraries/kube-jobs.git" }
