_target_: rationai.mlkit.lightning.loggers.MLFlowLogger
experiment_name: ${metadata.experiment_name}
run_name: ${metadata.run_name}
log_system_metrics: true
tags:
  mlflow.note.content: ${metadata.description}
