defaults:
  - hydra: default
  - logger: mlflow
  - _self_

seed: 0
mode: ???
checkpoint: null

trainer:
  max_epochs: 100
  sync_batchnorm: true
  precision: 32-true
  gradient_clip_val: 0.1
  callbacks:
    model_checkpoint:
      _target_: lightning.pytorch.callbacks.ModelCheckpoint
      save_top_k: 3
      save_last: true
      monitor: train/lejepa_loss
      mode: min
    monitor:
      _target_: lightning.pytorch.callbacks.DeviceStatsMonitor
      cpu_stats: true

model:
  warmup_steps: 1000
  lamb: 0.02

metadata:
  run_name: ???
  description: ???
  hyperparams: {}
