defaults:
  - hydra: default
  - logger: mlflow
  - _self_

seed: ${random_seed:}
mode: ???
checkpoint: null

trainer:
  strategy: deepspeed_stage_2
  num_nodes: 2
  precision: bf16-mixed
  gradient_clip_val: 0.1

data: {}

model: {}

metadata:
  experiment_name: ???
  run_name: ???
  description: ???
  hyperparams: {}
