defaults:
  - hydra: default
  - logger: mlflow
  - _self_

seed: ${random_seed:}
mode: ???
checkpoint: null

trainer:
  strategy: deepspeed_stage_2
  num_nodes: 2
  precision: bf16
  gradient_clip_val: 0.1

data: {}

model:
  dino:
    num_prototypes: 65536
    bottleneck_dim: 256
    num_layers: 3
    hidden_dim: 2048
  ibot:
    num_prototypes: 65536
    bottleneck_dim: 256
    num_layers: 3
    hidden_dim: 2048

metadata:
  experiment_name: ???
  run_name: ???
  description: ???
  hyperparams: {}
