defaults:
  - base
  - _self_

seed: 0
mode: ???
checkpoint: null

trainer:
  max_epochs: 10000
  sync_batchnorm: true
  log_every_n_steps: 10
  precision: bf16-mixed
  callbacks:
    model_checkpoint:
      _target_: lightning.pytorch.callbacks.ModelCheckpoint
      save_top_k: 3
      save_last: true
      monitor: train/lejepa_loss
      mode: min

model:
  warmup_steps: 1000
  lamb: 0.2
  n_concepts: 256
